// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

public class BattleEventListener: MonoBehaviour
{
	public UILabel self_blood;
	public UILabel self_level;
	public UILabel self_defense;
	public UILabel self_attack;

	public UILabel enemy_blood;
	public UILabel enemy_level;
	public UILabel enemy_defense;
	public UILabel enemy_attack;
	public BattleEventListener ()
	{
//		EventMgr.It.queueEvent (new BattleTurnInfoEvent ());
	}
	void Start () {
		System.Action<IEventType> callback = Battle_Turn_Info_Handler;
		EventMgr.It.register(new BattleTurnInfoEvent(),callback);
		//EventMgr.It.queueEvent (new BattleTurnInfoEvent ());
	}

	/**
	 * In charge of handling all UI events related to the battle_turn_info
	 **/
	private void Battle_Turn_Info_Handler(IEventType evnt){
		Debug.Log ("in battle turn infor handler");
		BattleTurnInfoEvent m_evnt = evnt as BattleTurnInfoEvent;
		Dictionary<string, int> self_dic = new Dictionary<string, int>();
		Dictionary<string, int> enemy_dic = new Dictionary<string, int>();
		self_blood.text = "12";
		self_level.text = "12";
		self_attack.text = "12";
		self_defense.text = "12";

		enemy_blood.text = "10";
		enemy_level.text = "10";
		enemy_defense.text = "10";
		enemy_attack.text = "10";


		self_dic = m_evnt.dictionary[0];
		enemy_dic = m_evnt.dictionary[1];
		int attack_damage = self_dic["attack_damage"];//damage taken at the end
		int defense_value = self_dic ["defense_value"];//damage blocked
		int current_turn_action = self_dic ["current_turn_action"];
		int qi = self_dic ["qi"];
		int blood = self_dic["blood"];
		int level = self_dic["level"];

		int e_attack_damage = enemy_dic["attack_damage"];//damage taken at the end
		int e_defense_value = enemy_dic ["defense_value"];//damage blocked
		int e_current_turn_action = enemy_dic ["current_turn_action"];
		int e_qi = enemy_dic ["qi"];
		int e_blood = enemy_dic["blood"];
		int e_level = enemy_dic["level"];
		Debug.Log ("self blood" + blood);


		//End of battle, send battle turn end event
		Send_Battle_Turn_End_Event ();
	}
	private void Send_Battle_Turn_End_Event(){
		EventMgr.It.queueEvent (new BattleTurnEndEvent());

	}
}


