// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public class BattleEventAttack:BattleEvent
{
	/**
	 * self id
	 * rhythm_quality: perfect(0)/great(1)/normal(2)/bad(3)
	 **/

	public BattleEventAttack ()
	{
		m_type = "BATTLEEVENTATTACK";
	}
	public string type	
	{
		get { return m_type; }
		set { m_type = value; }

	}

	public int self_id {
		get	{return m_self_id;}
		set {m_self_id = value;}
	}
	
	public int rhythm_quality{
		get {return m_rhythm_quality; } 
		set {m_rhythm_quality = value ; }
	}
	public int m_self_id;
	public int m_rhythm_quality;
	public string  m_type = "BATTLEEVENTATTACK";

}


