using UnityEngine;
using System.Collections;
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
public interface BattleEvent: IEventType
{
	//string m_type = "battletype";
	//int self_id;
	//string m_type = "BATTLEEVENT";
	
	//public string type
	//{
	//	get { return m_type; }
	//	set { m_type = value; }
	//}
}

