// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class BattleEventDefense:BattleEvent
{
	/**
	 * self id
	 * rhythm_quality: perfect(0)/great(1)/normal(2)/bad(3)
	 **/
	
	public BattleEventDefense ()
	{
		type = "battle event defense";
	}
	public string type
	{
		get { return type; }
		set { type = value; }
	}
	public int self_id{
		get { return self_id;}
		set { self_id = value;}
	}
	public int rhythm_quality{
		get{ return rhythm_quality;}
		set{ rhythm_quality = value;}
	}
	
}
