// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
/**
 * To start the new turn if this and rhythm is ready 
 **/
public class BattleTurnStartEvent:IEventType
{
	public string m_type = "BATTLETURNSTARTEVENT";

	public BattleTurnStartEvent ()
	{
		//type = "battle turn start event";
	}
	public string type
	{
		get { return m_type; }
		set { m_type = value; }
	}
}


